### PR TITLE
AMD-46 - Root Landing Page

### PR DESCRIPTION
**Pull request by Jtamedrano**

### CODE REVIEW

**Comment by Jtamedrano** [comment]
Going to add a basic hero

**Comment by Jtamedrano** [comment]
image

**Comment by Jtamedrano** [comment]
Related to [AMD-46]

[AMD-46]: https://newevolution.atlassian.net/browse/AMD-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by Kyleswillard — APPROVED** [review]
The general layout looks good!

**Pull request merged**
